spring:
  cloud:
    stream:
      # RocketMQ Binder 配置
      rocketmq:
        binder:
          # NameServer 地址
          name-server: ${refinex.rocketmq.name-server}

rocketmq:
  name-server: ${refinex.rocketmq.name-server}
  broker:
    # 项目中有两种方式使用了 RocketMQ, 其中通过 SpringCloud Stream 方式对 MQ 不强依赖, 即使没部署 RocketMQ 也能正常启动
    # 另外一种通过 MQ Client 的方式则强依赖 RocketMQ 的部署, 所以这里是用来控制避免对 RocketMQ 强依赖的
    # 如果你没有启动 RocketMQ, 又想把应用启动起来（不建议）,那么这里需要改成 false
    check: false