spring:
  cloud:
    stream:
      # RocketMQ Binder 配置
      rocketmq:
        binder:
          # NameServer 地址
          name-server: ${refinex.rocketmq.name-server:127.0.0.1:9876}
          # 默认 Producer Group (防止未配置时报错)
          group: ${spring.application.name}-group

      # Binding 配置示例 (业务方需要覆盖此部分)
      # bindings:
      #   tradeOrderOut-out-0:
      #     destination: TRADE_ORDER_TOPIC
      #     content-type: application/json

# Refinex 自定义配置
refinex:
  stream:
    enabled: true