# ============================================================
# Refinex 缓存配置（Redis + Redisson + JetCache）
# 发布到 Nacos: Group=REFINEX_SHARED
# ============================================================

spring:
  data:
    redis:
      # Redis 主机
      host: ${refinex.redis.url}
      # Redis 端口
      port: ${refinex.redis.port}
      # Redis 密码
      password: ${refinex.redis.password:}
      ssl:
        # 是否启用 Redis TLS
        enabled: ${refinex.redis.ssl-enabled:false}

  redis:
    redisson:
      # Redisson 原生配置（YAML 字符串）
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: ${refinex.redis.password}
          subscriptionsPerConnection: 5
          clientName: null
          # redis:// 或 rediss://
          address: "${refinex.redis.protocol:redis}://${refinex.redis.url}:${refinex.redis.port}"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.client.codec.StringCodec> {}
        transportMode: "NIO"

jetcache:
  # 统计日志输出间隔（分钟）
  statIntervalMinutes: 1
  # 是否将 area 放入缓存名
  areaInCacheName: false

  local:
    default:
      # 本地缓存实现
      type: caffeine
      # Key 转换器
      keyConvertor: fastjson2

  remote:
    default:
      # 远程缓存实现
      type: redisson
      keyConvertor: fastjson2
      # 广播通道（用于本地缓存失效通知）
      broadcastChannel: ${spring.application.name}
      # key 前缀（按服务隔离）
      keyPrefix: ${spring.application.name}
      # value 序列化策略
      valueEncoder: java
      valueDecoder: java
      # 默认过期时间（毫秒）
      defaultExpireInMillis: 5000
