# ============================================================
# Refinex Elasticsearch 配置
# 发布到 Nacos: Group=REFINEX_SHARED
# ============================================================

spring:
  elasticsearch:
    # 是否启用 Spring Elasticsearch
    enabled: ${refinex.elasticsearch.enabled:false}
    # ES 地址列表
    uris: ${refinex.elasticsearch.url:127.0.0.1:9200}
    # ES 用户名
    username: ${refinex.elasticsearch.username:}
    # ES 密码
    password: ${refinex.elasticsearch.password:}

easy-es:
  # 是否启用 Easy-ES
  enable: ${refinex.elasticsearch.enabled:false}
  # ES 地址
  address: ${refinex.elasticsearch.url:127.0.0.1:9200}
  # ES 用户名
  username: ${refinex.elasticsearch.username:}
  # ES 密码
  password: ${refinex.elasticsearch.password:}
  global-config:
    # 是否显示 Banner
    banner: false
    db-config:
      # 索引前缀
      table-prefix: ${refinex.elasticsearch.index-prefix:}
      # 字段策略
      field-strategy: NOT_NULL
