# ============================================================
# Refinex XXL-Job 配置
# 发布到 Nacos: Group=REFINEX_SHARED
# ============================================================

spring:
  xxl:
    job:
      # 是否启用 XXL-Job 执行器
      enabled: ${REFINEX_XXL_ENABLED:true}
      # 调度中心地址
      admin-addresses: ${refinex.xxl-job.admin-addresses}
      # 执行器名称
      app-name: ${refinex.xxl-job.app-name:${spring.application.name}}
      # 调度鉴权 token
      access-token: ${refinex.xxl-job.access-token}
      # 执行日志路径
      log-path: /data/applogs/xxl-job/jobhandler
      # 日志保留天数
      log-retention-days: 30
