# ============================================================
# Refinex 消息流配置（RocketMQ）
# 发布到 Nacos: Group=REFINEX_SHARED
# ============================================================

spring:
  cloud:
    stream:
      rocketmq:
        binder:
          # RocketMQ NameServer
          name-server: ${refinex.stream.name-server}

rocketmq:
  # 兼容直接使用 RocketMQ Client 的场景
  name-server: ${refinex.stream.name-server}
  broker:
    # 启动时是否强校验 Broker 可达
    check: false
