# ============================================================
# Refinex Sentinel 限流数据源配置
# 发布到 Nacos: Group=REFINEX_SHARED
# ============================================================

spring:
  cloud:
    sentinel:
      transport:
        # Sentinel Dashboard 地址
        dashboard: ${refinex.sentinel.dashboard}
      datasource:
        flow:
          nacos:
            # Nacos 地址
            server-addr: ${refinex.nacos.server-addr}
            # Nacos 命名空间
            namespace: ${refinex.nacos.namespace:public}
            # Nacos 用户名
            username: ${refinex.nacos.username:}
            # Nacos 密码
            password: ${refinex.nacos.password:}
            # 流控规则 DataId
            data-id: business-flow-rules
            # 规则分组
            group-id: SENTINEL_GROUP
            # 规则类型
            rule-type: FLOW
        param-flow:
          nacos:
            # Nacos 地址
            server-addr: ${refinex.nacos.server-addr}
            # Nacos 命名空间
            namespace: ${refinex.nacos.namespace:public}
            # Nacos 用户名
            username: ${refinex.nacos.username:}
            # Nacos 密码
            password: ${refinex.nacos.password:}
            # 热点规则 DataId
            data-id: business-param-flow-rules
            # 规则分组
            group-id: SENTINEL_GROUP
            # 规则类型
            rule-type: PARAM_FLOW
