# XXL-JOB 配置
spring:
  xxl:
    job:
      # 是否启用 XXL-JOB 执行器
      enabled: true
      # 调度中心地址, 如调度中心集群部署存在多个地址，则用逗号分隔。
      admin-addresses: ${refinex.xxl-job.admin-addresses}
      # 执行器名称
      app-name: ${refinex.xxl-job.app-name}
      # 执行器 AccessToken (安全性校验) 需与调度中心配置保持一致
      access-token: ${refinex.xxl-job.access-token}
      # 执行器注册 IP, 默认为空，表示自动获取 IP
      #ip:
      # 执行器端口, 默认 0 或 -1 表示自动寻找可用端口, 建议在 K8s 环境下显式指定，或使用 server.port + offset 策略
      #port:
      # 执行器运行日志文件存储磁盘路径, 建议配置为挂载卷路径，如 /var/logs/xxl-job/jobhandler
      log-path: /data/applogs/xxl-job/jobhandler
      # 调度中心日志保存天数, 过期日志自动清理，默认 30 天
      log-retention-days: 30