# ============================================================
# refinex-gateway 服务配置
# 发布到 Nacos: Group=REFINEX_SERVICE
# ============================================================

server:
  # Gateway 服务端口
  port: 8080

sa-token:
  # 网关层透传 Token 名称
  token-name: Refinex-Token

refinex:
  gateway:
    auth:
      # 网关登录校验白名单（无需 Token）
      exclude-paths:
        - /refinex-auth/auth/login
        - /refinex-auth/auth/sms/send
        - /refinex-auth/auth/email/send
        - /refinex-auth/auth/register
        - /refinex-auth/auth/password/reset
        - /wxPay/notify

spring:
  cloud:
    sentinel:
      transport:
        # Sentinel Dashboard 地址
        dashboard: ${refinex.sentinel.dashboard}
      datasource:
        gateway-flow:
          nacos:
            # Nacos 地址
            server-addr: ${refinex.nacos.server-addr}
            # Nacos 命名空间
            namespace: ${refinex.nacos.namespace:public}
            # Nacos 用户名
            username: ${refinex.nacos.username:}
            # Nacos 密码
            password: ${refinex.nacos.password:}
            # 网关流控规则 DataId
            data-id: refinex-gateway-flow-rules
            # 规则分组
            group-id: SENTINEL_GROUP
            # 规则类型
            rule-type: GW_FLOW

    gateway:
      server:
        webflux:
          globalcors:
            # 让 OPTIONS 预检在 SimpleUrlHandlerMapping 层直接处理，避免进入鉴权链
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                # 允许请求头
                allowedHeaders: '*'
                # 允许请求方法
                allowedMethods: '*'
                # 允许来源模式（allowCredentials=true 时不能使用 allowedOrigins='*'）
                allowedOriginPatterns: '*'
                # 是否允许携带 Cookie
                allowCredentials: true
          default-filters:
            # 去重 CORS 响应头
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
          routes:
            - id: refinex-auth
              uri: lb://refinex-auth
              predicates:
                - Path=/refinex-auth/**
              filters:
                - StripPrefix=1
            - id: refinex-user
              uri: lb://refinex-user
              predicates:
                - Path=/refinex-user/**
              filters:
                - StripPrefix=1
