# ============================================================
# refinex-system 服务配置
# 发布到 Nacos: Group=REFINEX_SERVICE
# ============================================================

server:
  # System 服务端口
  port: 8083

spring:
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 10MB
      # 单次请求最大大小
      max-request-size: 20MB
  cloud:
    openfeign:
      client:
        config:
          # 全局默认配置
          default:
            connect-timeout: 2000
            read-timeout: 5000
            logger-level: BASIC
          # refinex-user 服务专属配置
          refinex-user:
            connect-timeout: 2000
            read-timeout: 3000
