# ============================================================
# refinex-ai 服务配置
# 发布到 Nacos: Group=REFINEX_SERVICE
# ============================================================

server:
  # AI 服务端口
  port: 8084

spring:
  ai:
    chat:
      client:
        # 禁用 ChatClient 自动配置（由 ChatModelRouter 动态构建）
        enabled: false

  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 10MB
      # 单次请求最大大小
      max-request-size: 20MB

  http:
    clients:
      # HTTP Service Client 全局连接超时
      connect-timeout: 2s
      # HTTP Service Client 全局读取超时
      read-timeout: 5s
    serviceclient:
      refinex-user:
        # 用户服务调用地址
        base-url: lb://refinex-user
        # 用户服务读取超时
        read-timeout: 3s

sa-token:
  # 与网关/认证服务统一 Token Header 名称
  token-name: Refinex-Token

refinex:
  web:
    # 关闭 TokenFilter，统一使用 Sa-Token 进行鉴权
    enabled: false
